---
- hosts: webservers
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Remove Apache server
      yum: 
        name: httpd 
        state: absent
    
    - name: Remove index.html
      file:
        path: "{{ index_path }}"
        state: absent

    - name: Close http port
      firewalld:
        service: http
        permanent: true
        state: disabled
...