---
- hosts: webservers
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Remove net.ifnames if exist 
      replace:
        dest: "{{ grub_path }}"
        regexp: ' net.ifnames=.'
        replace: ''
        backup: yes

    - name: Remove biosdevname if exist 
      replace:
        dest: "{{ grub_path }}"
        regexp: ' biosdevname=.'
        replace: ''
        backup: yes
    
    - name: Add net.ifnames=0 biosdevname=0
      replace:
        dest: "{{ grub_path }}"
        regexp: 'GRUB_CMDLINE_LINUX="'
        replace: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0 '
        backup: yes

    - name: Run grub2-mkconfig
      ansible.builtin.command: grub2-mkconfig
...